const { Router } = require('express')
const authRouter = require('./authRouter')
const internAuthRouter = require('./internAuthRouter')
const clientAuthRouter = require('./clientAuthRouter')
const internDashboardRouter = require('./internDashboardRouter')
const registrationRouter = require('./registrationRouter')
const technologyRouter = require('./technologyRouter')
const syllabusRouter = require('./syllabusRouter')
const questionRouter = require('./questionRouter')
const testRouter = require('./testRouter')
const evaluationRouter = require('./evaluationRouter')
const taskRouter = require('./taskRouter')
const progressRouter = require('./progressRouter')
const noteRouter = require('./noteRouter')
const testSubmissionRouter = require('./testSubmissionRouter')
const notificationRouter = require('./notificationRouter')
const clientDailyNoteRouter = require('./clientDailyNoteRouter')
const adminDailyNoteRouter = require('./adminDailyNoteRouter')
const clientTestRouter = require('./clientTestRouter')
const assignCourseRouter = require('./assignCourseRouter')

const router = Router()

router.use('/admin', authRouter)
router.use('/intern', internAuthRouter)
router.use('/client', clientAuthRouter)
router.use('/intern/dashboard', internDashboardRouter)
router.use('/registrations', registrationRouter)
router.use('/technologies', technologyRouter)
router.use('/syllabus', syllabusRouter)
router.use('/questions', questionRouter)
router.use('/tests', testRouter)
router.use('/evaluations', evaluationRouter)
router.use('/tasks', taskRouter)
router.use('/progress', progressRouter)
router.use('/notes', noteRouter)
router.use('/test-submissions', testSubmissionRouter)
router.use('/notifications', notificationRouter)
router.use('/client/daily-notes', clientDailyNoteRouter)
router.use('/admin/daily-notes', adminDailyNoteRouter)
router.use('/client', clientTestRouter)
router.use('/admin', assignCourseRouter)

module.exports = router
